name: Upload to Cloudflare R2

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
        unzip awscli-bundle.zip
        sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

    - name: Configure AWS CLI for Cloudflare R2
      run: |
        aws configure set aws_access_key_id ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
      env:
        CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
        CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}

    - name: Upload to Cloudflare R2
      run: |
        aws s3 sync sources s3://${{ secrets.R2_BUCKET_NAME }}/post --endpoint-url=${{ secrets.R2_ENDPOINT_URL }} --delete
      env:
        R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
        R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}

    - name: Upload to Cloudflare R2
      run: |
        aws s3 sync public s3://${{ secrets.R2_PUBLIC_BUCKET_NAME }}/ --endpoint-url=${{ secrets.R2_ENDPOINT_URL }} --delete
      env:
        R2_BUCKET_NAME: ${{ secrets.R2_PUBLIC_BUCKET_NAME }}
        R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
